### ISSUE TITLE
SpamWa only one sanding

### ISSUE THREAD

**Issue by mrnose** [krypton-byte/SpamWa#8]
Mas bro, terimakasih sebelum nya aplikasi nya berjalan lancar tapi saat kirim spamwa, hanya berhasil 1 yang terkirim, izin minta penceramah, terimakasih

**Comment by tudes00** [comment]
Me too

**Comment by zohaib786-mirza** [comment]
Spamm Tokped +923165803054 Success!                                  
Traceback (most recent call last):                                           
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn                                                                     
    conn = connection.create_connection(                                     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection                                                         
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):   
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo             
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):  
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
socket.gaierror: [Errno -2] Name or service not known                        
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen                                                                   
    httplib_response = self._make_request(                                   
                       ^^^^^^^^^^^^^^^^^^^                                   
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 405, in _make_request                                                             
    self._validate_conn(conn)                                                
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1059, in _validate_conn                                                           
    conn.connect()                                                           
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 363, in connect                                                                       
    self.sock = conn = self._new_conn()                                      
                       ^^^^^^^^^^^^^^^^                                      
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn                                                                     
    raise NewConnectionError(                                                
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f58c85aead0>: Failed to establish a new connection: [Errno -2] Name or service not known                                                       
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send                                                                           
    resp = conn.urlopen(                                                     
           ^^^^^^^^^^^^^                                                     
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 800, in urlopen                                                                   
    retries = retries.increment(                                             
              ^^^^^^^^^^^^^^^^^^                                             
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment                                                                     
    raise MaxRetryError(_pool, url, error or ResponseError(cause))           
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cloud.altbalaji.com', port=443): Max retries exceeded with url: /accounts/mobile/verify?domain=ID (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f58c85aead0>: Failed to establish a new connection: [Errno -2] Name or service not known'))                                                    
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/home/kali/SpamWa/spam.py", line 302, in <module>                    
    jnspam()                                                                 
  File "/home/kali/SpamWa/spam.py", line 300, in jnspam                      
    main()                                                                   
  File "/home/kali/SpamWa/spam.py", line 258, in main                        
    single()                                                                 
  File "/home/kali/SpamWa/spam.py", line 166, in single                      
    print('\t'+z.balaji())                                                   
               ^^^^^^^^^^                                                    
  File "/home/kali/SpamWa/spam.py", line 91, in balaji                       
    req=requests.post(urlb,data=json.dumps(ata),headers=head)                
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                
  File "/usr/lib/python3/dist-packages/requests/api.py", line 115, in post   
    return request("post", url, data=data, json=json, **kwargs)              
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request 
    return session.request(method=method, url=url, **kwargs)                 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request                                                                        
    resp = self.send(prep, **send_kwargs)                                    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                    
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send                                                                           
    r = adapter.send(request, **kwargs)                                      
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                      
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send                                                                           
    raise ConnectionError(e, request=request)                                
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cloud.altbalaji.com', port=443): Max retries exceeded with url: /accounts/mobile/verify?domain=ID (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f58c85aead0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by zohaib786-mirza** [comment]
git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/zohaib786-mirza/zohaib786-mirza.git

**Comment by limitlless88** [comment]
bagaimana apk tersebut bisa digunakan di berbagai negara?
